# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iDnw74dK3WFkHg5k2mSIJ5hQzLVztsN3
"""

from google.colab import drive
drive.mount('/content/gdrive')

from numpy import genfromtxt
data_path = '/content/gdrive/MyDrive/AI Assignment/diabetes.csv'
Diabetes = genfromtxt(data_path, delimiter=',')

import random

random.shuffle(Diabetes)

import numpy as np


Train_set=[]
Val_set=[]
Test_set=[]

for S in Diabetes:
 R=random.randrange(1,100)
 if R>=1 and R<=70:
    Train_set.append(S)
 elif R>=70 and R<=85:
    Val_set.append(S)
 else:
    Test_set.append(S)

import  math
K=1

Error=0
_col=len(Train_set[0])
validation=len(Val_set)

for V in Val_set:
  
  L=[]
 
  
  for T in Train_set:
   
    distance=0
    M=[]
     
     
    for x in range(0,(_col-1)):
      distance+=(V[x]-T[x])**2
    b=math.sqrt(distance) 
    M.append(T[_col-1])
    M.append(b)
    L.append(M)
   
  sort=sorted(L,key=lambda x:x[1])
  f=np.array(sort)
  y=0
  for r in range(0,K):
    y=y+f[r,0]
  prediction=y/K
  Error=Error+(V[_col-1]-prediction)**2

M_Error=Error/validation
M_Error