# -*- coding: utf-8 -*-
"""Iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12HULdQX7aCQl3TKvOK8TCjwbEhg8eIMI
"""

from google.colab import drive
drive.mount('/content/gdrive')

from numpy import genfromtxt
data_path = '/content/gdrive/MyDrive/AI Assignment/iris.csv'
iris = genfromtxt(data_path, delimiter=',')

import random

random.shuffle(iris)

import numpy as np


Train_set=[]
Val_set=[]
Test_set=[]

for S in iris:
 R=random.randrange(1,100)
 if R>=1 and R<=70:
    Train_set.append(S)
 elif R>=70 and R<=85:
    Val_set.append(S)
 else:
    Test_set.append(S)

import  math
K=3

c=0
_col=len(Train_set[0])
validation=len(Val_set)

for V in Val_set:
  
  L=[]
 
 
  for T in Train_set:

    distance=0
    M=[]
     
     
    for x in range(0,(_col-1)):
      distance+=(V[x]-T[x])**2
    b=math.sqrt(distance) 
    M.append(T[_col-1])
    M.append(b)
    L.append(M)
   
  sort=sorted(L,key=lambda x:x[1])
  f=np.array(sort)
  zero=0
  one=0
  two=0
  for r in range(0,K):
    if f[r,0]==0:
      zero=zero+1;
    elif f[r,0]==1:
      one=one+1;
    elif f[r,0]==2:
      two=two+1;
  if (zero>=one) and (zero>=two):
    a=0;
  elif(one>=zero) and (one>=two):
    a=1
  else:
    a=2
  if a==V[_col-1]:
    c=c+1;
acurrecy=(c/validation)*100

acurrecy